### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by collinzimm** [saowwapark/inCNV#1]
Hello,  When trying to run this software I run into an issue when I attempt to install inCNV with docker-compose up -d. 

Pulling incnv-db (sakkayaphab/incnv-db:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling incnv-db (sakkayaphab/incnv-db:latest)...
ERROR: pull access denied for sakkayaphab/incnv-db, repository does not exist or may require 'docker login'

I am using docker desktop and am logged in.

**Comment by saowwapark** [comment]
I apologize for replying late.

I changed many things in the code without checking. And it automatically create a new image. Now I've already fixed it at [inCNV v2.2.0](https://github.com/saowwapark/inCNV/releases/tag/v2.2.0)
 
*FYI, I removed all the old versions because the codes are so confused.*
